name: Update RSS Feed

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install requests feedgenerator

    - name: Run script to fetch and update RSS feed
      run: |
        python scripts/example_json_pull.py  # Fetch the new data
        python scripts/create_rss_feed.py    # Update the RSS feed with new data

    - name: Commit and push changes
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "youremail@example.com"
        git add feed.xml
        git commit -m "Updated RSS feed with new documents"
        git push
