name: Update RSS Feed

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install requests feedgenerator

    - name: Run script to fetch and update RSS feed
      run: |
        python scripts/json_pull.py  # Run the json_pull.py script directly

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the GitHub token stored in secrets
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/rkoens/ease.git  # Authenticate using the token
        git add feed.xml
        git commit -m "Updated RSS feed with new documents"
        git push origin HEAD:main  # Push changes
