name: Update RSS Feed

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install requests feedgenerator

    - name: Run script to fetch and update RSS feed
      run: |
        python scripts/json_pull.py  # Run the json_pull.py script directly

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://github.com/rkoens/ease.git
    
        # Stage feed.xml if it exists
        if [ -f feed.xml ]; then
          git add feed.xml
          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Updated RSS feed with new documents"
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/rkoens/ease.git HEAD:main
          fi
        else
          echo "feed.xml does not exist yet"
        fi

